{
 "title": "Geth node (detailed)",
 "description": "Geth metrics overview dashboard.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(chain_head_block, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_head_block{}, instance)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "system"
    },
    {
     "expr": "system_cpu_syswait{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "system_cpu_procload{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_allocs{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "ingress"
    },
    {
     "expr": "rate(p2p_egress{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "dials"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "serves"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "eth_db_chaindata_disk_write{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } }
 ]
}